### ISSUE TITLE
[REWARDS] Cosmetic events to help with reward distribution

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-ethereum-contracts-v2#42]
I'm starting to think about the reward distributor. To assist with the implementation I think two new cosmetic events will help me in `IStakingRewards`:

* `RewardDistributionStarted(uptoBlock, split)`
* `RewardDistributionEnded(uptoBlock)`

The validator wakes up and decides to distribute rewards - so they choose a period they distribute for (up to some Ethereum block number) and calculate the balance they plan to distribute.

Since the distribution for the period can take some time and multiple transactions, it may crash in the middle so I need to keep the state somewhere. I'd like the client to be completely stateless, so if it dies, it could reconstruct all state from Ethereum.. These events will let me know if I'm in the middle of a distribution that didn't finish yet. If indeed I'm in the middle, I will also get the split (between validator and delegators) to make sure we continue the same split during the distribution.

These two events will be emitted when calling two new dedicated functions that emit them. I will call these functions in the distributor.

**Comment by OdedWx** [comment]
Even though it's more expensive, we can also add a tag determined by the Guardian to all distribution events (similar to the tags the current reward distribution events emits)

**Comment by vistra** [comment]
If the client is stateless there is also the issue of multiple distribution calls executing in the same time. A possible solution is to make sure a delegator can receive rewards only once per distribution period.

**Comment by talkol** [comment]
It's not that the client is completely stateless. It will have in-memory state generated from synchronizing on events (which can take a long time). If the client terminates, this state will reset and will need to be generated again.

As long as we output events on distribution we should be able to reconstruct everything.

**Comment by vistra** [comment]
What I meant is that if the flow you described runs twice, in parallel, it could assign rewards twice to the same validator. For instance if the user launches the process twice at the same time.

**Comment by talkol** [comment]
Yes, good point. There are concurrency issues.

I'm not positive we have to protect against these since only the validator can distribute from their address. So this means they're pretty insane to distribute twice in parallel, they need to sign each transaction in both, it's not like they won't know.

**Comment by OdedWx** [comment]
Proposal: 

// Per Tx
event StakingRewardsDistributionEvent(address indexed distributer, uint256 fromBlock, uint256 toBlock, uint256 txTotal, uint256 distributedSoFar, string Metadata);
event StakingRewardsDistributed(address indexed assignee, uint256 amount);

//Interface
function distributeOrbsTokenRewards(uint256 totalAmounts, address[] calldata to, uint256[] calldata amounts,
                                    uint256 fromBlock, uint256 toBlock, uint256 distributedSoFar, string Metadata) external;

Notes:
* fromBlock, toBlock, Metadata, distributedSoFar are set by the distributed and are not enforced by the contract.

**Comment by talkol** [comment]
In `StakingRewardsDistributed` we can remove `totalAmount ` since we now have all the detailed amounts

**Comment by talkol** [comment]
What is the first allowed `fromBlock`?

**Comment by vistra** [comment]
0?

**Comment by talkol** [comment]
0 but can't be any higher, meaning the contract must verify it's 0. If it doesn't, then the delegate can make a mistake and input too high of a value and block themselves for ever distributing.

**Comment by talkol** [comment]
One more thing we forgot is the split. Meaning how much delegators get (eg. 70%). The reason it's important is that we can't have somebody change the split in the middle of a distribution so I'd like to know what it was.

**Comment by vistra** [comment]
We should also require that all block numbers (from block, to block) are in the past.

**Comment by ronnno** [comment]
echoing my comments on #45:

some questions about the API:
- we force spanning all block numbers from 0 onward inclusively even for periods when the validator was not in committee. it's not very intuitive and takes away some information. I'd suggest to allow leaving gaps in block heights so that distribution event history will correctly describe the terms for which rewards were granted.
- we're mixing a strict approach of never allowing to go back in block numbers, with a lenient approach of implicitly closing a distribution by sending a transaction for a distribution in a later batch. It's too easy to close a batch as we are not declaring the expected total amounts or any sort of commitment while the batch is supposed to be all thought out when it first starts. feels error prone. I'd consider:
  - adding methods to abort the distribution batch state and allow to begin from the middle.
  - changing `totalAmount` to mean the entire distribution batch - and disallow progressing to the next batch before either completing the distribution or aborting it explicitly
  - allow starting a distribution batch at any block height and ending at any (later) block height as long as we are not in the middle of a prior batch


What do you think?

**Comment by ronnno** [comment]
update - the points above discussed and rejected.

@vistra  can we close this issue?

**Comment by vistra** [comment]
#45
