### ISSUE TITLE
vote out (banning) votes checking for stakes owners on delegation changes

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#46]
The issue here is who's vote-out votes to check when staking/delegation changes occur. 

since staking changes affect the total governance stakes all outstanding votes should be reevaluated to check for banning or unbanning. But outstanding votes are potentially a long list and not practical to check all of them. we currently check any identity which is directly involved in the staking/delegation event. 

Since this approach is not exhaustive the question comes up if we can maybe check less identities - to save gas.

@vistra please clarify if you feel I missed the point.
@vistra wrote:

A bit out of scope for this PR, but Isn't this redundant?

_Originally posted by @vistra in https://github.com/orbs-network/orbs-ethereum-contracts-v2/pull/44_

**Comment by vistra** [comment]
On stake change, we call `_applyStakesToBanningBy` to update the votes of (not for) both the stake owner and the delegate. But I think that only the delegate matters, because:
1. If the stake owner hasn't delegated, then is it the delegate.
2. If the stake owner did delegate, then its gov stake was 0 before is is 0 now, so it's voting power hasn't changed.
Did I miss anything?

**Comment by ronnno** [comment]
Regarding 2:
- Even if the voting power of the stake owner did not change, the total governance stakes may have changed meaning that reevaluating the votes could still lead to a new outcome.

I agree it's a weak point and we can expect a new vote to be cast in case the vote out needs to be refreshed.. what do you think?

Also, what do you think about `notifyDelegationChange`? we currently recheck the votes cast by the old delegate and the new delegate. do you see justification for excluding one of these checks as well?

**Comment by vistra** [comment]
The stake owner in this scenario doesn't have voting power, which is just as saying that they didn't vote at all. So the implications of checking their votes is entirely coincidental and you could just as well randomly choose an unrelated participant and check it's votes. 

`notifyDelegationChangez is a bit different because the delegation action changed (removed or added) the votes of the delegator. So this is consistent with checking the votes when votes change.

**Comment by ronnno** [comment]
I agree, the idea was to maximize the checking with any address I could put my hands on, I agree the added value seems marginal at best.
