### ISSUE TITLE
Flaky test: "should distribute fees to validators in general and compliance committees"

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-ethereum-contracts-v2#54]
sometimes the expected reward is off by 1 and the test fails

**Comment by ronnno** [comment]
see 
https://circleci.com/gh/orbs-network/orbs-ethereum-contracts-v2/260?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by vistra** [comment]
Probably because of the remainder assignment logic. The tests and the rewards contract use a different ordering of the committee, which means that when the remainder is assigned (which is not always the case - hence the flakiness), it may be assigned to a different members by the contract and the test.
