### ISSUE TITLE
notifyReadyForCommittee tx signed using orbsAddress and not address

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-ethereum-contracts-v2#65]
https://github.com/orbs-network/orbs-ethereum-contracts-v2/blob/52f5965321938cca364121058982871b5db85df9/test/driver.ts#L288

```
async notifyReadyForCommittee() {
        return await this.elections.notifyReadyForCommittee({from: this.orbsAddress});
    }

    async notifyReadyToSync() {
        return await this.elections.notifyReadyToSync({from: this.orbsAddress});
    }
```

I'm working on the integration test and there the orbsAddress is not from the HDWallet accounts, it's completely separate. Because it's used as the `from` here, HDWallet attempts to sign with it and complains that it's an unknown account.

**Comment by ronnno** [comment]
@talkol whats the use case here? to sign these transactions we need access to the secret (mnemonic?) for these addresses.

I assume you are using the public access setter to override the orbs address for these validator objects.

can you provide a mnemonic to sign these transactions? or do you have a web3/provider instance already associated with the correct HDWallet?

**Comment by talkol** [comment]
I am confused on why we have both an Orbs address for a node and an Ethereum address.
It would have made sense if we only signed Ethereum transactions using the Ethereum address, but why do we need to sign Ethereum transactions from the Orbs address?

**Comment by ronnno** [comment]
this is to separate the keys the validator uses for his identity and financial/governance actions from the keys stored in the node vault.

Alternately, if you create a second instance of the driver then its easier to give a new driver a different mnemonic. this will require a fix but possible if you can separate the drivers you use for validator actions and for orbs node actions.
If you can easily to the two types of operations from different processes we don't need any change to that code since you can override the default mnemonic in one process (env var `ETHEREUM_MNEMONIC`).

Last option - if you set `ETHEREUM_MNEMONIC` to the same mnemonic you used to generate the Orbs address, that will also work - that is possibly the easiest setup but we should be careful of collisions since the driver uses addresses pretty freely. there are a couple of "reserved" addresses it does not use. 

I suggest a quick talk with @vistra and @OdedWx  possibly @netoneko since I'm not sure how you are obtaining these addresses (nebula?)

**Comment by talkol** [comment]
Closed as intended behavior, staging environment fixed in https://github.com/orbs-network/release-to-staging/commit/2d91c54ca926d6b7a3fd06a89ddf6aaaa518761e
